# Generated by Django 4.2.3 on 2023-08-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='movie_title',
            new_name='movie',
        ),
    ]
