# Generated by Django 4.2.3 on 2023-08-26 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaapp', '0002_rename_movie_title_ticket_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='movie',
        ),
        migrations.AddField(
            model_name='ticket',
            name='movie_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinemaapp.movie'),
            preserve_default=False,
        ),
    ]
